# **Assignment 4**

In [6]:
import numpy as np

### *Task 1*

In [7]:
temprature_data = np.random.randint(low = -10, high = 41, size = (500, 365))
temprature_data

array([[ 26,  13,   4, ...,  -9,  -1,  -9],
       [ 30,  26,  20, ...,  17,  22, -10],
       [ 36,   8,   4, ...,  35,   7,  31],
       ...,
       [  3,  30,  37, ...,  13,  30,  24],
       [ 18,  -2,   4, ...,   5,  30,  29],
       [ 15,  -7,  -2, ...,  24,  15,  23]], dtype=int32)

In [8]:
humidity_data = np.random.uniform(low = 0, high = 101, size = (500, 365))
humidity_data

array([[97.88860859, 21.28523777, 53.52725826, ..., 42.17475107,
        56.78893333, 40.09458217],
       [40.50501884, 71.51649057, 89.51544917, ..., 73.52631861,
         8.97183037, 67.74628038],
       [ 4.50501444, 46.21545629,  0.6209623 , ..., 99.07597474,
        52.77162406, 57.42703113],
       ...,
       [ 7.464033  , 93.07785951, 54.43759909, ..., 38.72179691,
        96.7351577 , 63.75441989],
       [51.69837665, 30.80988044, 91.76068292, ..., 69.56953838,
        91.73733981, 94.17017972],
       [59.16097465, 54.61231107, 86.90295366, ..., 18.93056384,
        95.07400178, 72.35146021]])

### *Task 2*

In [10]:
missing = int(0.05 * 500 * 365)
missing_temp = (np.random.randint(0, 500, missing),
                        np.random.randint(0, 365, missing))
missing_hum = (np.random.randint(0, 500, missing),
                       np.random.randint(0, 365, missing))

In [ ]:
temprature_data[missing_temp] = 0
total_temp = np.where(temprature_data == 0)
len(total_temp[0])

12305

In [11]:
humidity_data[missing_hum] = 0
total_hum = np.where(humidity_data == 0.0)
len(total_hum[0])

8899

### *Task 3*

In [ ]:
temprature_f = (temprature_data * 9/5) + 32
discomf = temprature_f + (0.1 * humidity_data)
discomf = np.where(discomf > 80, 80, discomf)
discomf

### *Task 4*

In [12]:
January = np.average(temprature_data[:,:31])
January

np.float64(15.033483870967743)

### *Task 5*

In [13]:
np.where(temprature_data > 35, 0, temprature_data)
nulls = (temprature_data == 0).sum(axis = 1)
nulls

array([ 8,  7, 10, 13, 10,  5,  7,  5,  7, 12,  8,  9,  8,  2,  4, 11, 11,
        3,  7,  6,  5,  6,  8,  7,  8,  8,  3,  4, 13,  4,  4,  9,  4,  8,
        9,  7,  8, 11,  7,  5,  4,  4,  7, 10, 10,  4, 12,  7,  7,  3,  6,
        7,  9, 10, 10,  4,  8, 14,  4,  9,  7,  6,  6,  2, 10,  6, 13,  8,
       15, 12,  9,  7,  8,  4, 13,  8,  4,  7,  9,  3,  5,  6,  7,  6,  8,
        9,  7,  4,  6,  4, 14,  8,  6,  6,  6,  8,  6,  8,  5, 16,  4,  4,
       11,  6,  8,  7,  9,  6,  5,  9, 11,  7, 11,  5,  9, 10,  6, 11,  8,
        6,  6, 11,  9,  6,  8,  7,  6,  7,  6,  9,  6,  7, 12,  6,  7,  9,
        8,  6,  5,  7,  6,  8,  7,  6, 11,  6, 11,  7,  4,  9,  7,  9, 10,
       10,  6,  7,  6, 13,  7,  7,  4,  2,  6,  6, 12,  8,  8,  6,  3,  6,
       11,  7,  4,  7,  7,  9,  8,  9,  1, 12,  5, 13,  9,  6,  9,  7,  8,
        6,  7,  9,  8,  5,  6,  5,  8,  2,  3, 10,  5,  5,  6,  7,  6, 12,
       13,  9,  8, 12,  7,  8, 10,  6,  6,  7,  8,  9,  7,  4,  8,  6, 12,
        8,  8,  5, 12,  5

### *Task 6*

In [14]:
q1 = temprature_data[:, :91]
q2 = temprature_data[:, 91:183]
q3 = temprature_data[:, 183:275]
q4 = temprature_data[:, 175:366]
print(np.mean(q1), np.mean(q2), np.mean(q3), np.mean(q4))


14.94865934065934 14.98408695652174 14.95395652173913 14.93078947368421


### *Task 7*

In [15]:
dry = np.where(humidity_data < 30.0, "Dry", humidity_data)
humid = np.where(humidity_data > 70.0, "Humid", humidity_data)
dry_d = np.sum(dry == "Dry", axis=1)
humid_d = np.sum(humid == "Humid", axis=1)
print(dry_d, '\n\n', humid_d)

[125 108 127 121 121 114 113 120 109 119 124 130 126 120 116 118 106 120
 120 112 127 124 118 126 129 123 131 120 123 120 123 128 131 132 148 127
 131 126 138 134 120 103 114 127 123 119 135 124 123 131 138 108 125 105
 131 118 117 118 121 107 122 118 117 116 133 125 108 111 108 105 121 124
 132 117 122 106 125 118 129 121 128 140 128 135 124 132 123 117 127 112
 106 109 121 119 107 114 112 112 129 123 135 119 123 131 119 130 125 118
 120 121 130 127 126 115 116 136 119 106 131 126 118 120 124 123 113 116
 128 113 117 142 120 119 126 101 135 102 124 121 116 116 128 126 110 117
 115 117 118 131 115 118 114 128 122 120 123  92 119 135 119 132 116 124
 132 109 136 126 130 128 105 124 105 112 113 122 124 108 132 107 128 124
 119 127 110 120 113 130 130 112 115 109 111 125 136 121 128 123 130 110
 113 127 124 127 114 118 137 116 116 123 123 124 135 124 114 123 127 131
 125 107 129 131 137 118 120 111 128 124 125 121 116 133 120 116 117 144
 115 127 118 112 111 136 129 117 104 136 123 127 10

### *Task 8*

In [16]:
trend = np.random.normal(0, 0.5, 365)
adjusted = temprature_data + trend
adjusted

array([[ 26.14564488,  12.69641434,   4.06444275, ...,  -8.21588213,
         -1.44502358,  -9.22975503],
       [ 30.14564488,  25.69641434,  20.06444275, ...,  17.78411787,
         21.55497642, -10.22975503],
       [ 36.14564488,   7.69641434,   4.06444275, ...,  35.78411787,
          6.55497642,  30.77024497],
       ...,
       [  3.14564488,  29.69641434,  37.06444275, ...,  13.78411787,
         29.55497642,  23.77024497],
       [ 18.14564488,  -2.30358566,   4.06444275, ...,   5.78411787,
         29.55497642,  28.77024497],
       [ 15.14564488,  -7.30358566,  -1.93555725, ...,  24.78411787,
         14.55497642,  22.77024497]])